runtime: nodejs20
env: standard

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

  - url: /(.*)
    static_files: \1
    upload: (.*)
    secure: always